global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'monitoring-backend'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']  # f√ºr Mac/Windows Docker Desktop
