global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'quarkus-app-8099'
    metrics_path: '/q/metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8099'

  - job_name: 'quarkus-app-8090'
    metrics_path: '/q/metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8090'
