global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # --- Local Healthchecks ---
  - job_name: 'blackbox_http_local'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://localhost:8090/q/health
          - http://localhost:8099/q/health
          - http://localhost:8095/q/health
          - http://localhost:8091/q/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # --- SourceSystems via Quarkus ---
  - job_name: 'blackbox_http_sourceSystems'
    metrics_path: /probe
    params:
      module: [http_2xx]
    http_sd_configs:
      - url: http://localhost:8090/api/monitoring/prometheus/flat/sources
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_http_sd_target]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # --- TargetSystems via Quarkus ---
  - job_name: 'blackbox_http_targetSystems'
    metrics_path: /probe
    params:
      module: [http_2xx]
    http_sd_configs:
      - url: http://localhost:8090/api/monitoring/prometheus/flat/targets
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_http_sd_target]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # --- All endpoints (Source + Target zusammen, wenn /flat/all implementiert) ---
  - job_name: 'blackbox_http_all'
    metrics_path: /probe
    params:
      module: [http_2xx]
    http_sd_configs:
      - url: http://localhost:8090/api/monitoring/prometheus/flat/all
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_http_sd_target]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # --- Dummy URLs direkt ---
  - job_name: 'blackbox_http_dummy'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://localhost:8090/api/monitoring/prometheus/flat/targets

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: dummy_urls
      - target_label: __address__
        replacement: blackbox_exporter:9115




