global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'monitoring-backend'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8093']

  - job_name: 'monitoring-backend-health'
    metrics_path: '/health/live'
    static_configs:
      - targets: ['host.docker.internal:8093']
